# Generated by Django 5.2.17 on 2026-09-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(upload_to='posts/%Y/%m/%d/'),
        ),
    ]
