# Generated by Django 5.2.17 on 2026-08-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=175)),
                ('Title', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
    ]
