"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

def env_flag(name, default="0"):
    """Read a boolean from the environment. Anything unlisted is False."""
    return os.environ.get(name, default).strip().lower() in {"1", "true", "yes", "on"}


# Settings that differ between a laptop and a server are read from the
# environment. Nothing secret is written in this file, because this file is in
# git and git remembers forever.
DEBUG = env_flag("DJANGO_DEBUG", "1")

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if not DEBUG:
        # Fail loudly. A missing key that silently falls back to a known value
        # is worse than a crash: every signature the site makes is forgeable.
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set when DEBUG is off. "
            "Generate one with: python -c "
            "'from django.core.management.utils import get_random_secret_key as k; print(k())'"
        )
    SECRET_KEY = "django-insecure-dev-only-never-deploy-this-key"

# `ALLOWED_HOSTS` is the Host-header allowlist. Empty + DEBUG=True quietly means
# localhost only; empty + DEBUG=False rejects every request.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if host.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

   # user-defined apps and 3rd party apps
    'blog',
    'palshare',
    'drf_spectacular',
    'accounts',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # WHO ARE YOU — how a request is turned into `request.user`.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    # WHAT MAY YOU DO — the default answer for every view that does not
    # override it. Closed by default: a new endpoint is private until its
    # author decides otherwise.
    #
    # This replaces `DjangoModelPermissionsOrAnonReadOnly`, which was pasted in
    # from the drf-spectacular README and is wrong twice over: it lets anonymous
    # callers read everything, and it ties writes to `auth_permission` rows, so
    # a perfectly valid JWT still gets a 403.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # HOW OFTEN — the cheapest defence against credential stuffing and scraping.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "60/min",
        "user": "240/min",
        # Views that set `throttle_scope = "auth"` — login and register.
        "auth": "5/min",
    },
    # HOW MUCH — an unpaginated list endpoint is a denial-of-service tool that
    # you built and shipped yourself.
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# Throttle counters live in the cache. The default local-memory cache is
# per-process, so two gunicorn workers keep two separate counts — real
# deployments point this at Redis or Memcached.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "django-lab-throttling",
    }
}

# Rate limits for the plain-Django HTML pages. DRF's DEFAULT_THROTTLE_RATES
# cover DRF views only — a function view in blog/views.py is invisible to them,
# so the pages carry their own table, read by blog/throttling.py.
PAGE_THROTTLE_RATES = {
    "blog-detail": "30/min",
}


SIMPLE_JWT = {
    # Short-lived, because an access token cannot be revoked: until it expires,
    # whoever holds it is you.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    # Every refresh issues a new refresh token and blacklists the old one, so a
    # stolen refresh token is usable at most once before it starts failing.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # Tokens are signed with SECRET_KEY. Rotate the key and every token dies.
    "SIGNING_KEY": SECRET_KEY,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Your Project API',
    'DESCRIPTION': 'Your project description',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}

# Where @login_required sends an anonymous visitor. The default is
# /accounts/login/, which in this project is the JSON login endpoint — a page
# no browser can render a form for.
LOGIN_URL = "/admin/login/"

# Third-party API keys, read from the environment like everything else secret.
# Both are optional: `palshare/integrations.py` returns None without them and
# the widgets render their empty states. See .env.example.
WEATHER_API_KEY = os.environ.get("WEATHER_API_KEY", "")
NVIDIA_API_KEY = os.environ.get("NVIDIA_API_KEY", "")
LOGIN_REDIRECT_URL = "/blogs/posts/"

# ---------------------------------------------------------------------------
# Security headers and cookies
#
# `python manage.py check --deploy` is the checklist these settings answer to.
# ---------------------------------------------------------------------------

# Never render this site inside someone else's <iframe> (clickjacking).
X_FRAME_OPTIONS = "DENY"
# Do not let a browser second-guess a Content-Type it was given.
SECURE_CONTENT_TYPE_NOSNIFF = True
# Do not leak the full URL of this site in the Referer header of outbound links.
SECURE_REFERRER_POLICY = "same-origin"

if not DEBUG:
    # Everything below is a no-op on http://127.0.0.1, and mandatory in front
    # of a real domain.
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365  # one year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Behind a TLS-terminating proxy, this is how Django learns the original
    # request was HTTPS. Only set it if the proxy strips a client-sent header.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
