# Generated by Django 5.2.17 on 2026-09-07 05:43

import django.core.validators
import django.db.models.deletion
import palshare.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.FileField(blank=True, upload_to='palshare/avatars/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palshare_assistant_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('user', 'You'), ('assistant', 'Assistant')], max_length=9)),
                ('text', models.TextField(validators=[palshare.models.validate_text])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='palshare.assistantthread')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[palshare.models.validate_text])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palshare_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='palshare.comment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='palshare.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palshare_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('participant_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palshare_conversations_one', to=settings.AUTH_USER_MODEL)),
                ('participant_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palshare_conversations_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palshare_following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palshare_followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[palshare.models.validate_text])),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='palshare.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palshare_sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('followers_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palshare_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='palshare/posts/%Y/%m/')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='palshare.post')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palshare_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='palshare.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='palshare.post'),
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='palshare.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palshare_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='palshare.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palshare_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='assistantthread',
            index=models.Index(fields=['user', 'created_at', 'id'], name='palshare_as_user_id_4b3cfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='assistantturn',
            constraint=models.UniqueConstraint(fields=('thread', 'position'), name='ps_assistant_turn_position'),
        ),
        migrations.AddConstraint(
            model_name='assistantturn',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['user', 'assistant'])), name='ps_assistant_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='ps_comment_like_unique'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_one', 'updated_at'], name='palshare_co_partici_6a6bff_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_two', 'updated_at'], name='palshare_co_partici_ec0764_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('participant_one__lt', models.F('participant_two'))), name='ps_conversation_ordered_pair'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('participant_one', 'participant_two'), name='ps_conversation_pair_unique'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'status'], name='palshare_fo_followe_3eb8da_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following', 'status'], name='palshare_fo_followi_ccead9_idx'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='ps_follow_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='ps_follow_not_self'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', True), ('status', 'pending')), models.Q(('accepted_at__isnull', False), ('status', 'accepted')), _connector='OR'), name='ps_follow_acceptance_valid'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sent_at', 'id'], name='palshare_me_convers_b2b2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'read_at', 'sender'], name='palshare_me_convers_33d365_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('read_at__isnull', True), ('read_at__gte', models.F('sent_at')), _connector='OR'), name='ps_message_read_after_sent'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at', 'id'], name='palshare_po_created_33e15d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'created_at', 'id'], name='palshare_po_author__d32881_idx'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(fields=('post', 'position'), name='ps_media_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 0), ('position__lte', 3)), name='ps_media_four_slots'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['image', 'video'])), name='ps_media_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='ps_like_user_post_unique'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent', 'created_at', 'id'], name='palshare_co_post_id_f73e03_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='ps_comment_not_own_parent'),
        ),
        migrations.AddIndex(
            model_name='save',
            index=models.Index(fields=['user', 'created_at', 'id'], name='palshare_sa_user_id_e1400e_idx'),
        ),
        migrations.AddConstraint(
            model_name='save',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='ps_save_user_post_unique'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='ps_share_user_post_unique'),
        ),
    ]
